services:
  postgres:
    image: postgres:16-alpine
    container_name: ic-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile

    container_name: rmp-api

    restart: unless-stopped

    command: sh -c "cd packages/database && npx prisma generate && npx prisma db push --accept-data-loss && npx tsx prisma/seed-event.ts && cd ../../apps/api && npm run start"

    environment:
      NODE_ENV: production

      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_ALLOWED_DOMAINS: ${GOOGLE_ALLOWED_DOMAINS}
      CORS_ORIGIN: ${CORS_ORIGIN}
      AISENSY_API_KEY: ${AISENSY_API_KEY}
      SUPER_ADMIN_NAME: ${SUPER_ADMIN_NAME}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - "${API_PORT}:4000"

    depends_on:
      postgres:
        condition: service_healthy

  induction-portal:
    build:
      context: .
      dockerfile: apps/induction-portal/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    container_name: rmp-web

    restart: unless-stopped

    environment:
      NODE_ENV: production
      # Specify API URL for the client/server
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL: http://api:4000/api

    ports:
      - "${WEB_PORT:-3000}:3000"

    depends_on:
      - api
      
  events-portal:
    build:
      context: .
      dockerfile: apps/events-portal/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    container_name: rmp-events

    restart: unless-stopped

    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      API_URL: http://api:4000/api

    ports:
      - "3002:3002"

    depends_on:
      - api
    
volumes:
  postgres_data: