export const NOTICES_DATA = [
  {
    id: 'notice-1',
    title: 'Startup Pitch Day – Apply by 20 June',
    date: '15 June 2025',
    url: '/notices/startup-pitch-day-2025',
    isPinned: true,
  },
  {
    id: 'notice-2',
    title: 'Office Closed on 18 June for Maintenance',
    date: '14 June 2025',
    url: '/notices/office-closed-june-18',
    isPinned: true,
  },
  {
    id: 'notice-3',
    title: 'AI/ML Ideathon 2025 – Register Now!',
    date: '13 June 2025',
    url: '/notices/ai-ml-ideathon',
    isPinned: false,
  },
  {
    id: 'notice-4',
    title: 'Incubation Applications Open for July Cohort',
    date: '10 June 2025',
    url: '/notices/july-incubation-call',
    isPinned: false,
  },
  {
    id: 'notice-5',
    title: 'Guest Talk by Zomato CTO – 21 June',
    date: '09 June 2025',
    url: '/notices/zomato-cto-guest-talk',
    isPinned: false,
  },
  {
    id: 'notice-6',
    title: 'Demo Day Presentation Templates Available',
    date: '08 June 2025',
    url: '/notices/demo-day-template',
    isPinned: false,
  },
  {
    id: 'notice-7',
    title: 'UI/UX Bootcamp for Founders – June 25–26',
    date: '07 June 2025',
    url: '/notices/uiux-bootcamp-2025',
    isPinned: false,
  },
  {
    id: 'notice-8',
    title: 'Internship Drive with Partner Startups',
    date: '06 June 2025',
    url: '/notices/startup-internship-drive',
    isPinned: false,
  },
  {
    id: 'notice-9',
    title: 'Result Announcement: May Pitch Round',
    date: '04 June 2025',
    url: '/notices/pitch-round-results',
    isPinned: false,
  },
  {
    id: 'notice-10',
    title: 'New 3D Printer Available in Maker Lab',
    date: '02 June 2025',
    url: '/notices/new-3d-printer',
    isPinned: false,
  },
];
